name = 'hugo-sandbox'
compatibility_date = "2025-06-25"

routes = [
  { pattern = "hugo-asandbox.willduncan.com", custom_domain = true }
]

[build]
command = "./build.sh"

[assets]
directory = "./public"
not_found_handling = "404-page"